### ISSUE TITLE
This doesn't work on different networks

### ISSUE THREAD

**Issue by abhinav1992** [mgiuliani/webrtc-video-chat#4]
The demo will work on the same network but will not work on different networks. Like If I use it in my local system then it will work, when I use it in a LAN then also it will work but if I use it like one pc is connected to Wi-fi and I am connecting with mobile that is connected on 3G network, then it will fail to transfer media.

**Comment by acddev** [comment]
Any idea why this is the case?

**Comment by Pwnmanship** [comment]
Anyone got an idea why this only works on local network?

**Comment by edufranzoni** [comment]
Anyone got an idea why this only works on local network? [2] 
@mgiuliani hi?

**Comment by mgiuliani** [comment]
@edufranzoni thanks for your PR and for the interest in this proj.  Honestly, I haven't touched this demo project, or WebRTC in general, in six years.  At the time I wrote this, the WebRTC APIs were under pretty heavy churn.  On top of it, I know that SignalR has come a long way since then, so I'd be surprised if that piece is even stable.  If I can find some time here, I'll pull this back down and see if it rings any bells, but just want to be honest with the state of this thing :)

**Comment by mgiuliani** [comment]
Alright, loaded this back up, surprised everything just works, ha!  It appears to be a connection resolution problem.  Back when I initially wrote this, a STUN server was sufficient to get the media connection going across the public internet.  After some testing, I am seeing the same results as posted here.

I went ahead and added a TURN server for handling the media connection to the list of ICE addresses, and the public connections started working just fine.  Unfortunately I don't have a public TURN server to point you to - my understanding is that they simply eat too much bandwidth for something to be available for free public consumption.  [Twilio offers them as a service though](https://www.twilio.com/stun-turn/pricing).

There are also some [Docker containers](https://hub.docker.com/r/instrumentisto/coturn) with pre-configured TURN servers that may work for you.

Once you have a TURN server, you can just add it to the `_iceServers` collection in `connectionManager.js`:

```
_iceServers = [
            {
                urls: 'stun:74.125.142.127:19302'
            },
            {
                urls: 'turn:xxx.xxx.xxx',
                credential: 'password',
                username: 'username'
            }
        ]
```
